#lang racket

(define (l str)
  (string-length str))

(define length (- (+ (* (l "one") 190)
                  (* (l "two") 190)
                  (* (l "three") 190)
                  (* (l "four") 190)
                  (* (l "five") 190)
                  (* (l "six") 190)
                  (* (l "seven") 190)
                  (* (l "eight") 190)
                  (* (l "nine") 190)
                  (* (l "ten") 10)
                  (* (l "eleven") 10)
                  (* (l "twelve") 10)
                  (* (l "thirteen") 10)
                  (* (l "fourteen") 10)
                  (* (l "fifteen") 10)
                  (* (l "sixteen") 10)
                  (* (l "seventeen") 10)
                  (* (l "eighteen") 10)
                  (* (l "nineteen") 10)
                  (* (l "twenty") 100)
                  (* (l "thirty") 100)
                  (* (l "fourty") 100)
                  (* (l "fifty") 100)
                  (* (l "sixty") 100)
                  (* (l "seventy") 100)
                  (* (l "eighty") 100)
                  (* (l "ninety") 100)
                  (* (l "and") (* 99 9))
                  (* (l "hundred") 900)
                  (l "onethousand")) 100))